# ::: Code Generated by Copilot abcdef01-2345-6789-abcd-ef0123456789. This comment will be removed automatically after the file is saved :::
#!/bin/bash

echo "🚀 Starting Kafka Management UI (Local Development Mode)"
echo "======================================================"

# Check if Node.js is available
if ! command -v node &> /dev/null; then
    echo "❌ Node.js is not installed. Please install Node.js and try again."
    exit 1
fi

# Check if npm is available
if ! command -v npm &> /dev/null; then
    echo "❌ npm is not installed. Please install npm and try again."
    exit 1
fi

echo "📦 Installing dependencies..."
npm install

if [ $? -ne 0 ]; then
    echo "❌ Failed to install dependencies. Trying with different settings..."
    npm config set strict-ssl false
    npm config set registry http://registry.npmjs.org/
    npm install
fi

if [ $? -ne 0 ]; then
    echo "❌ Failed to install npm dependencies. Please check your internet connection."
    exit 1
fi

echo "🔧 Starting Kafka UI server..."
echo "📝 Note: Make sure Kafka is running on localhost:9092"
echo "🌐 The UI will be available at: http://localhost:3333"
echo ""

# Set environment variable for local Kafka
export KAFKA_BROKERS=localhost:9092
export PORT=3333

# Start the server
npm start
